# docker-compose.yml
version: "3.9"
services:
  api:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [postgres]
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432" # para permitir consulta desde dbeaver
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
