version: '3.8'
services:
  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
